// Server side of the staging `wp_color_management_v1` protocol.
//
// This is the *detection* foundation for dynamic HDR. It does two things:
//
//   (a) advertises that the compositor's OUTPUT is HDR-capable (PQ transfer /
//       BT.2020 primaries + the same mastering / content-light-level constants
//       Wolf already stamps onto its P010 caps) so HDR clients enable their HDR
//       path, and
//   (b) tracks, per `wl_surface`, the image description (colorspace) a client
//       sets, so downstream code can ask `surface_is_hdr(&surface)`.
//
// Everything here is gated behind the `WOLF_HDR_CM` env var at the global-creation
// site in `State::new`; when unset the global is never advertised and none of this
// code runs, so client behaviour is exactly as before.
//
// The bindings are the ones generated by the `wayland-protocols` crate (staging +
// server features, enabled transitively by smithay's `wayland_frontend`); we
// implement `GlobalDispatch`/`Dispatch` straight onto `State`, the same way the
// rest of the smithay protocol handlers do.

use std::cell::{Cell, RefCell};
use std::sync::Mutex;
use std::sync::atomic::{AtomicU32, Ordering};

use smithay::reexports::wayland_protocols::wp::color_management::v1::server::{
    wp_color_management_output_v1::{self, WpColorManagementOutputV1},
    wp_color_management_surface_feedback_v1::{self, WpColorManagementSurfaceFeedbackV1},
    wp_color_management_surface_v1::{self, WpColorManagementSurfaceV1},
    wp_color_manager_v1::{
        self, Feature, Primaries, RenderIntent, TransferFunction, WpColorManagerV1,
    },
    wp_image_description_creator_params_v1::{self, WpImageDescriptionCreatorParamsV1},
    wp_image_description_info_v1::WpImageDescriptionInfoV1,
    wp_image_description_v1::{self, WpImageDescriptionV1},
};
use smithay::reexports::wayland_server::{
    Client, DataInit, Dispatch, DisplayHandle, GlobalDispatch, New, Resource, WEnum,
    Weak as WlWeak, backend::ClientId, protocol::wl_surface::WlSurface,
};
use smithay::wayland::compositor::with_states;

use crate::comp::State;

/// CIE 1931 xy chromaticities of the BT.2020 / BT.2100 primaries and the D65 white
/// point, each coordinate multiplied by 1,000,000 (the protocol's fixed-point unit).
/// Order is r_x, r_y, g_x, g_y, b_x, b_y, w_x, w_y. These are the same primaries Wolf
/// already advertises in `HDR_MASTERING` (there scaled by 50,000 instead of 1,000,000).
const BT2020_PRIMARIES: [i32; 8] = [
    708000, 292000, 170000, 797000, 131000, 46000, 312700, 329000,
];

/// Image-description id-number source. The protocol only requires that two protocol
/// objects share an identity iff they refer to the same underlying record; handing out
/// a fresh id per created description is spec-compliant (it merely prevents clients from
/// de-duplicating). Id 0 is reserved as invalid, so we start at 1.
static NEXT_IMAGE_DESC_ID: AtomicU32 = AtomicU32::new(1);

fn next_identity() -> u32 {
    NEXT_IMAGE_DESC_ID.fetch_add(1, Ordering::Relaxed)
}

/// Mastering display (target color volume) of an image description: SMPTE ST 2086
/// primaries (chromaticities * 1,000,000) plus the mastering luminance range
/// (`min_lum` * 10,000 cd/m², `max_lum` cd/m²).
#[derive(Debug, Clone, Copy)]
pub struct MasteringDisplay {
    pub primaries: [i32; 8],
    pub min_lum: u32,
    pub max_lum: u32,
}

/// A resolved, immutable image description. `transfer`/`primaries` are the named
/// values; the rest is HDR static metadata. `is_hdr` is derived from PQ + BT.2020.
#[derive(Debug, Clone, Default)]
pub struct ImageDescription {
    pub transfer: Option<TransferFunction>,
    pub primaries: Option<Primaries>,
    pub primaries_chromaticity: Option<[i32; 8]>,
    /// Primary color volume luminance: (min * 10000, max, reference white).
    pub luminances: Option<(u32, u32, u32)>,
    pub mastering: Option<MasteringDisplay>,
    pub max_cll: Option<u32>,
    pub max_fall: Option<u32>,
}

/// The per-`wl_surface` colour state set through `set_image_description`. This is the
/// detection payload downstream code reads via [`surface_is_hdr`].
#[derive(Debug, Clone, Default)]
pub struct SurfaceColorState {
    pub transfer: Option<TransferFunction>,
    pub primaries: Option<Primaries>,
    pub mastering: Option<MasteringDisplay>,
    pub max_cll: Option<u32>,
    pub max_fall: Option<u32>,
}

impl SurfaceColorState {
    /// A surface is treated as HDR when its image description is BT.2100 PQ:
    /// SMPTE ST 2084 (PQ) transfer + BT.2020 primaries.
    pub fn is_hdr(&self) -> bool {
        self.transfer == Some(TransferFunction::St2084Pq)
            && self.primaries == Some(Primaries::Bt2020)
    }
}

impl From<&ImageDescription> for SurfaceColorState {
    fn from(desc: &ImageDescription) -> Self {
        SurfaceColorState {
            transfer: desc.transfer,
            primaries: desc.primaries,
            mastering: desc.mastering,
            max_cll: desc.max_cll,
            max_fall: desc.max_fall,
        }
    }
}

/// The HDR image description handed back for the (single) output: BT.2100 PQ /
/// BT.2020 with the same mastering-display + content-light-level constants Wolf uses
/// (`HDR_MASTERING` / `HDR_CLL` in the gst plugin): BT.2020 primaries, 1000-nit max /
/// 0.0001-nit min, MaxCLL 1000, MaxFALL 400.
fn hdr_output_description() -> ImageDescription {
    ImageDescription {
        transfer: Some(TransferFunction::St2084Pq),
        primaries: Some(Primaries::Bt2020),
        primaries_chromaticity: Some(BT2020_PRIMARIES),
        // PQ default luminances per the protocol: min 0.005, max 10000, reference 203.
        luminances: Some((50, 10000, 203)),
        mastering: Some(MasteringDisplay {
            primaries: BT2020_PRIMARIES,
            min_lum: 1, // 0.0001 cd/m² * 10000
            max_lum: 1000,
        }),
        max_cll: Some(1000),
        max_fall: Some(400),
    }
}

// --- per-resource user data --------------------------------------------------------

/// User data of a `wp_image_description_v1`: the resolved description, its identity and
/// whether `get_information` is permitted (only the output's description allows it).
#[derive(Debug)]
pub struct ImageDescriptionData {
    pub identity: u32,
    pub desc: ImageDescription,
    pub allow_info: bool,
}

/// User data of a `wp_color_management_surface_v1` / `_surface_feedback_v1`: the
/// associated surface (weak, so surface destruction makes the object inert).
#[derive(Debug)]
pub struct ColorSurfaceData(Mutex<WlWeak<WlSurface>>);

impl ColorSurfaceData {
    fn new(surface: &WlSurface) -> Self {
        ColorSurfaceData(Mutex::new(surface.downgrade()))
    }

    fn surface(&self) -> Option<WlSurface> {
        self.0.lock().unwrap().upgrade().ok()
    }
}

/// Accumulator behind a `wp_image_description_creator_params_v1`: each `set_*` request
/// fills one slot exactly once (re-setting raises the `already_set` protocol error).
#[derive(Debug, Default)]
pub struct ParamsBuilder {
    transfer: Option<TransferFunction>,
    primaries: Option<Primaries>,
    mastering_primaries: Option<[i32; 8]>,
    mastering_luminance: Option<(u32, u32)>,
    max_cll: Option<u32>,
    max_fall: Option<u32>,
    luminances_set: bool,
}

/// User data of a `wp_image_description_creator_params_v1`.
#[derive(Debug, Default)]
pub struct ParamsData(Mutex<ParamsBuilder>);

// --- surface data_map markers ------------------------------------------------------

/// Marks that a `wp_color_management_surface_v1` is already attached to a surface, so a
/// second `get_surface` for the same surface raises `surface_exists`.
#[derive(Default)]
struct ColorSurfaceAttached(Cell<bool>);

/// Read the HDR flag a client set on `surface` (false if none / not color-managed).
///
/// This is the detection entry point downstream code uses: `true` means the client
/// declared the surface as BT.2100 PQ (PQ transfer + BT.2020 primaries).
pub fn surface_is_hdr(surface: &WlSurface) -> bool {
    with_states(surface, |states| {
        states
            .data_map
            .get::<RefCell<Option<SurfaceColorState>>>()
            .map(|cell| cell.borrow().as_ref().is_some_and(|s| s.is_hdr()))
            .unwrap_or(false)
    })
}

/// Apply (`Some`) or clear (`None`) the colour state stored in a surface's `data_map`,
/// logging the HDR transition so it can be observed on the target device.
fn set_surface_color_state(surface: &WlSurface, new: Option<SurfaceColorState>) {
    with_states(surface, |states| {
        let cell = states
            .data_map
            .get_or_insert::<RefCell<Option<SurfaceColorState>>, _>(|| RefCell::new(None));
        let was_hdr = cell.borrow().as_ref().is_some_and(|s| s.is_hdr());
        let now_hdr = new.as_ref().is_some_and(|s| s.is_hdr());
        *cell.borrow_mut() = new;
        if now_hdr && !was_hdr {
            tracing::info!(surface = ?surface.id(), "color_mgmt: surface -> HDR (PQ/BT2020)");
        } else if was_hdr && !now_hdr {
            tracing::info!(
                surface = ?surface.id(),
                "color_mgmt: surface -> SDR (HDR image description cleared)"
            );
        }
    });
}

/// Send the full description of `desc` over a freshly created `wp_image_description_info_v1`
/// and finish with `done` (which destroys the info object).
fn send_image_description_info(info: &WpImageDescriptionInfoV1, desc: &ImageDescription) {
    if let Some(c) = desc.primaries_chromaticity {
        info.primaries(c[0], c[1], c[2], c[3], c[4], c[5], c[6], c[7]);
    }
    if let Some(p) = desc.primaries {
        info.primaries_named(p);
    }
    if let Some(tf) = desc.transfer {
        info.tf_named(tf);
    }
    if let Some((min, max, reference)) = desc.luminances {
        info.luminances(min, max, reference);
    }
    if let Some(m) = &desc.mastering {
        let p = m.primaries;
        info.target_primaries(p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7]);
        info.target_luminance(m.min_lum, m.max_lum);
    }
    if let Some(v) = desc.max_cll {
        info.target_max_cll(v);
    }
    if let Some(v) = desc.max_fall {
        info.target_max_fall(v);
    }
    info.done();
}

/// Create a `wp_image_description_v1` for `desc`, wire up its user data and immediately
/// send `ready` (we never produce descriptions asynchronously, so they are ready at once).
fn init_ready_image_description(
    desc: ImageDescription,
    allow_info: bool,
    new_id: New<WpImageDescriptionV1>,
    data_init: &mut DataInit<'_, State>,
) {
    let identity = next_identity();
    let image_desc = data_init.init(
        new_id,
        ImageDescriptionData {
            identity,
            desc,
            allow_info,
        },
    );
    image_desc.ready(identity);
}

// --- wp_color_manager_v1 -----------------------------------------------------------

impl GlobalDispatch<WpColorManagerV1, ()> for State {
    fn bind(
        _state: &mut State,
        _dh: &DisplayHandle,
        _client: &Client,
        resource: New<WpColorManagerV1>,
        _global_data: &(),
        data_init: &mut DataInit<'_, State>,
    ) {
        let manager = data_init.init(resource, ());

        // Advertise everything the parametric creator below actually accepts. The
        // `done` event terminates the burst.
        manager.supported_intent(RenderIntent::Perceptual);

        manager.supported_feature(Feature::Parametric);
        manager.supported_feature(Feature::SetMasteringDisplayPrimaries);
        manager.supported_feature(Feature::SetLuminances);

        for tf in [
            TransferFunction::Srgb,
            TransferFunction::Gamma22,
            TransferFunction::Bt1886,
            TransferFunction::St2084Pq,
            TransferFunction::Hlg,
        ] {
            manager.supported_tf_named(tf);
        }

        for primaries in [Primaries::Srgb, Primaries::DisplayP3, Primaries::Bt2020] {
            manager.supported_primaries_named(primaries);
        }

        manager.done();
    }
}

impl Dispatch<WpColorManagerV1, ()> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        manager: &WpColorManagerV1,
        request: wp_color_manager_v1::Request,
        _data: &(),
        _dh: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        use wp_color_manager_v1::Request;
        match request {
            Request::GetOutput { id, .. } => {
                data_init.init(id, ());
            }
            Request::GetSurface { id, surface } => {
                let already = with_states(&surface, |states| {
                    let marker = states
                        .data_map
                        .get_or_insert::<ColorSurfaceAttached, _>(ColorSurfaceAttached::default);
                    let was = marker.0.get();
                    marker.0.set(true);
                    was
                });
                if already {
                    manager.post_error(
                        wp_color_manager_v1::Error::SurfaceExists,
                        "a wp_color_management_surface_v1 already exists for this surface",
                    );
                } else {
                    data_init.init(id, ColorSurfaceData::new(&surface));
                }
            }
            Request::GetSurfaceFeedback { id, surface } => {
                data_init.init(id, ColorSurfaceData::new(&surface));
            }
            Request::CreateParametricCreator { obj } => {
                data_init.init(obj, ParamsData::default());
            }
            Request::CreateIccCreator { .. } => {
                manager.post_error(
                    wp_color_manager_v1::Error::UnsupportedFeature,
                    "ICC image descriptions are not supported",
                );
            }
            Request::CreateWindowsScrgb { .. } => {
                manager.post_error(
                    wp_color_manager_v1::Error::UnsupportedFeature,
                    "windows_scrgb is not supported",
                );
            }
            Request::Destroy => {}
            _ => {}
        }
    }
}

// --- wp_color_management_output_v1 -------------------------------------------------

impl Dispatch<WpColorManagementOutputV1, ()> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        _output: &WpColorManagementOutputV1,
        request: wp_color_management_output_v1::Request,
        _data: &(),
        _dh: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        use wp_color_management_output_v1::Request;
        match request {
            Request::GetImageDescription { image_description } => {
                // The output is HDR-capable; hand back the PQ / BT.2020 description.
                init_ready_image_description(
                    hdr_output_description(),
                    true,
                    image_description,
                    data_init,
                );
            }
            Request::Destroy => {}
            _ => {}
        }
    }
}

// --- wp_color_management_surface_v1 ------------------------------------------------

impl Dispatch<WpColorManagementSurfaceV1, ColorSurfaceData> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        obj: &WpColorManagementSurfaceV1,
        request: wp_color_management_surface_v1::Request,
        data: &ColorSurfaceData,
        _dh: &DisplayHandle,
        _data_init: &mut DataInit<'_, State>,
    ) {
        use wp_color_management_surface_v1::Request;
        match request {
            Request::SetImageDescription {
                image_description,
                render_intent,
            } => {
                let Some(surface) = data.surface() else {
                    obj.post_error(
                        wp_color_management_surface_v1::Error::Inert,
                        "the underlying wl_surface is gone",
                    );
                    return;
                };
                // We only advertise the (mandatory) perceptual intent.
                if !matches!(render_intent, WEnum::Value(RenderIntent::Perceptual)) {
                    obj.post_error(
                        wp_color_management_surface_v1::Error::RenderIntent,
                        "unsupported rendering intent",
                    );
                    return;
                }
                let Some(desc) = image_description.data::<ImageDescriptionData>() else {
                    obj.post_error(
                        wp_color_management_surface_v1::Error::ImageDescription,
                        "unknown image description object",
                    );
                    return;
                };
                set_surface_color_state(&surface, Some(SurfaceColorState::from(&desc.desc)));
            }
            Request::UnsetImageDescription => {
                let Some(surface) = data.surface() else {
                    obj.post_error(
                        wp_color_management_surface_v1::Error::Inert,
                        "the underlying wl_surface is gone",
                    );
                    return;
                };
                set_surface_color_state(&surface, None);
            }
            Request::Destroy => {
                // Destroying behaves like unset_image_description, and frees the slot so
                // a fresh wp_color_management_surface_v1 may be created for the surface.
                if let Some(surface) = data.surface() {
                    set_surface_color_state(&surface, None);
                    with_states(&surface, |states| {
                        if let Some(marker) = states.data_map.get::<ColorSurfaceAttached>() {
                            marker.0.set(false);
                        }
                    });
                }
            }
            _ => {}
        }
    }
}

// --- wp_color_management_surface_feedback_v1 ---------------------------------------

impl Dispatch<WpColorManagementSurfaceFeedbackV1, ColorSurfaceData> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        _obj: &WpColorManagementSurfaceFeedbackV1,
        request: wp_color_management_surface_feedback_v1::Request,
        _data: &ColorSurfaceData,
        _dh: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        use wp_color_management_surface_feedback_v1::Request;
        match request {
            // The preferred description is the HDR-capable output description.
            Request::GetPreferred { image_description }
            | Request::GetPreferredParametric { image_description } => {
                init_ready_image_description(
                    hdr_output_description(),
                    true,
                    image_description,
                    data_init,
                );
            }
            Request::Destroy => {}
            _ => {}
        }
    }
}

// --- wp_image_description_creator_params_v1 ----------------------------------------

impl Dispatch<WpImageDescriptionCreatorParamsV1, ParamsData> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        obj: &WpImageDescriptionCreatorParamsV1,
        request: wp_image_description_creator_params_v1::Request,
        data: &ParamsData,
        _dh: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        use wp_image_description_creator_params_v1::{Error, Request};

        // Helper: a `set_*` request on an already-set slot is a protocol error.
        macro_rules! already_set {
            ($cond:expr) => {
                if $cond {
                    obj.post_error(Error::AlreadySet, "property already set");
                    return;
                }
            };
        }

        match request {
            Request::SetTfNamed { tf } => {
                let WEnum::Value(tf) = tf else {
                    obj.post_error(Error::InvalidTf, "unknown transfer function");
                    return;
                };
                let mut b = data.0.lock().unwrap();
                already_set!(b.transfer.is_some());
                b.transfer = Some(tf);
            }
            Request::SetPrimariesNamed { primaries } => {
                let WEnum::Value(primaries) = primaries else {
                    obj.post_error(Error::InvalidPrimariesNamed, "unknown named primaries");
                    return;
                };
                let mut b = data.0.lock().unwrap();
                already_set!(b.primaries.is_some());
                b.primaries = Some(primaries);
            }
            Request::SetMasteringDisplayPrimaries {
                r_x,
                r_y,
                g_x,
                g_y,
                b_x,
                b_y,
                w_x,
                w_y,
            } => {
                let mut b = data.0.lock().unwrap();
                already_set!(b.mastering_primaries.is_some());
                b.mastering_primaries = Some([r_x, r_y, g_x, g_y, b_x, b_y, w_x, w_y]);
            }
            Request::SetMasteringLuminance { min_lum, max_lum } => {
                if max_lum <= min_lum {
                    obj.post_error(Error::InvalidLuminance, "max_lum must exceed min_lum");
                    return;
                }
                let mut b = data.0.lock().unwrap();
                already_set!(b.mastering_luminance.is_some());
                b.mastering_luminance = Some((min_lum, max_lum));
            }
            Request::SetLuminances {
                min_lum: _,
                max_lum: _,
                reference_lum: _,
            } => {
                // Accepted (we advertise set_luminances) but not needed for detection.
                let mut b = data.0.lock().unwrap();
                already_set!(b.luminances_set);
                b.luminances_set = true;
            }
            Request::SetMaxCll { max_cll } => {
                data.0.lock().unwrap().max_cll = Some(max_cll);
            }
            Request::SetMaxFall { max_fall } => {
                data.0.lock().unwrap().max_fall = Some(max_fall);
            }
            // Features we do not advertise.
            Request::SetTfPower { .. } => {
                obj.post_error(Error::UnsupportedFeature, "set_tf_power is not supported");
            }
            Request::SetPrimaries { .. } => {
                obj.post_error(Error::UnsupportedFeature, "set_primaries is not supported");
            }
            Request::Create { image_description } => {
                let b = data.0.lock().unwrap();
                // tf + primaries are the required properties for a complete set.
                if b.transfer.is_none() || b.primaries.is_none() {
                    obj.post_error(
                        Error::IncompleteSet,
                        "transfer characteristic and primaries are required",
                    );
                    return;
                }
                let mastering = b.mastering_primaries.map(|primaries| {
                    let (min_lum, max_lum) = b.mastering_luminance.unwrap_or((0, 0));
                    MasteringDisplay {
                        primaries,
                        min_lum,
                        max_lum,
                    }
                });
                let desc = ImageDescription {
                    transfer: b.transfer,
                    primaries: b.primaries,
                    primaries_chromaticity: None,
                    luminances: None,
                    mastering,
                    max_cll: b.max_cll,
                    max_fall: b.max_fall,
                };
                drop(b);
                // Params-created descriptions do not allow get_information.
                init_ready_image_description(desc, false, image_description, data_init);
            }
            _ => {}
        }
    }
}

// --- wp_image_description_v1 -------------------------------------------------------

impl Dispatch<WpImageDescriptionV1, ImageDescriptionData> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        obj: &WpImageDescriptionV1,
        request: wp_image_description_v1::Request,
        data: &ImageDescriptionData,
        _dh: &DisplayHandle,
        data_init: &mut DataInit<'_, State>,
    ) {
        use wp_image_description_v1::Request;
        match request {
            Request::GetInformation { information } => {
                if !data.allow_info {
                    obj.post_error(
                        wp_image_description_v1::Error::NoInformation,
                        "get_information is not allowed on this image description",
                    );
                    return;
                }
                let info = data_init.init(information, ());
                send_image_description_info(&info, &data.desc);
            }
            Request::Destroy => {}
            _ => {}
        }
    }
}

// --- wp_image_description_info_v1 (events only) ------------------------------------

impl Dispatch<WpImageDescriptionInfoV1, ()> for State {
    fn request(
        _state: &mut State,
        _client: &Client,
        _obj: &WpImageDescriptionInfoV1,
        _request: <WpImageDescriptionInfoV1 as Resource>::Request,
        _data: &(),
        _dh: &DisplayHandle,
        _data_init: &mut DataInit<'_, State>,
    ) {
        // wp_image_description_info_v1 has no requests.
    }

    fn destroyed(
        _state: &mut State,
        _client: ClientId,
        _obj: &WpImageDescriptionInfoV1,
        _data: &(),
    ) {
    }
}
